# Generated by Django 2.2.9 on 2020-01-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20200124_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='max_round',
            field=models.PositiveSmallIntegerField(default=1, editable=False, help_text='The last round the player made it to'),
        ),
    ]
